sudo: required

language: ruby

rvm:
  - 2.2.3

git:
  depth: 25

services:
  - docker

env:
  - PGPASSWORD=travis_pg_test

before_install:
  - sudo /etc/init.d/postgresql stop
  - docker build -t rmarchei/gisgraphy .
  - docker run -d -e POSTGRES_PASSWORD=$PGPASSWORD --name gisgraphy-db rmarchei/gisgraphy-db && sleep 10
  - docker run -d -p 127.0.0.1:8080:8080 --link gisgraphy-db:postgres --name gisgraphy rmarchei/gisgraphy
  - timeout 20 docker logs -f gisgraphy || true
  - docker ps -a
  - docker top gisgraphy
  - docker exec -it gisgraphy id
  - docker exec -it gisgraphy pwd

script:
  - curl -sLo /dev/null -w "%{http_code}" http://localhost:8080/login.jsp | grep -q 200
